# Generated by Django 4.0.6 on 2022-07-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reveal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='no product name', max_length=100),
        ),
    ]
