# Generated by Django 4.0.6 on 2022-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reveal_app', '0002_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='no product name', max_length=100),
        ),
    ]
